const initialState = {
  post: null,
  posts: {
    result: [],
    filters: {
      cityId: '10',
      locationIds: '',
      dealType: 'sale',
      priceMin: 0,
      priceMax: 0,
      roomsMin: 0,
      roomsMax: 0,
      estateType: null,
      apartmentType: null,
      sqmMin: 0,
      sqmMax: 0,
      livingSqmMin: 0,
      livingSqmMax: 0,
      kitchenSqmMin: 0,
      kitchenSqmMax: 0,
      totalFloorMin: 0,
      totalFloorMax: 0,
      floorMin: 0,
      floorMax: 0,
      documented: false,
      mortgage: false,
      redevelopment: false,
      haggle: false,
      notFirstFloor: false,
      notLastFloor: false,
    },
    pagination: {
      skipped: null,
      current: 1,
      total: null,
    },
  },
  postForm: {
    _id: null,
    userType: '',
    city: '',
    district: '',
    subdistrict: '',
    address: '',
    searchArea: [0, 0],
    location: [0, 0],
    estateType: '',
    apartmentType: '',
    dealType: '',
    rooms: 0,
    sqm: 0,
    livingRoomsSqm: 0,
    kitchenSqm: 0,
    floor: 0,
    totalFloors: 0,
    renovation: '',
    redevelopment: false,
    ceilingHeight: 0,
    yearBuild: 0,
    elevator: false,
    parkingLot: false,
    documented: false,
    mortgage: false,
    kidsAllowed: false,
    petsAllowed: false,
    balcony: false,
    bathroomType: '',
    windows: 0,
    frontWindow: false,
    rearWindow: false,
    furniture: false,
    kitchenFurniture: false,
    cabelTv: false,
    phone: false,
    internet: false,
    electricity: false,
    gas: false,
    water: false,
    heating: false,
    tv: false,
    conditioner: false,
    washingMachine: false,
    dishwasher: false,
    refrigerator: false,
    description: '',
    price: 0,
    haggle: false,
    installmentOfPayment: false,
    prepayment: false,
    municipalServicesIncluded: false,
    images: [],
    username: '',
    contact: '',
  },
  formSteps: { currentStep: 0, totalSteps: 7 },
  validationErrors: {},
  error: {},
}

export default initialState
