export default {
  post: null,
  posts: {
    result: [],
    filters: {
      cityId: '10',
      dealType: 'sale',
      priceMin: 0,
      priceMax: 0,
      rooms: 0,
      estateType: null,
      sqmMin: 0,
      sqmMax: 0,
      livingSqmMin: 0,
      livingSqmMax: 0,
      kitchenSqmMin: 0,
      kitchenSqmMax: 0,
      totalFloorMin: 0,
      totalFloorMax: 0,
      floorMin: 0,
      floorMax: 0,
      documented: false,
      mortgage: false,
      redevelopment: false,
      bargain: false,
      notFirstFloor: false,
      notLastFloor: false
    },
    pagination: {
      skipped: null,
      current: 1,
      total: null
    }
  },
  postForm: {
    userType: '',
    city: '',
    district: '',
    subdistrict: '',
    address: '',
    searchArea: [0, 0],
    cityLocation: [49.9673008918762, 40.4929150268958],
    location: [0, 0],
    estateType: '',
    apartmentType: '',
    dealType: '',
    rooms: 0,
    sqm: 0,
    livingRoomsSqm: 0,
    kitchenSqm: 0,
    floor: 0,
    totalFloors: 0,
    maintenance: '',
    redevelopment: false,
    ceilingHeight: 0,
    yearBuild: 0,
    elevator: false,
    parkingLot: false,
    documented: false,
    mortgage: false,
    kidsAllowed: false,
    petsAllowed: false,
    balcony: false,
    bathroomType: '',
    windows: 0,
    frontWindow: false,
    rearWindow: false,
    furniture: false,
    kitchenFurniture: false,
    cctv: false,
    phone: false,
    internet: false,
    electricity: false,
    gas: false,
    water: false,
    heating: false,
    tv: false,
    conditioner: false,
    washingMachine: false,
    dishwasher: false,
    refrigerator: false,
    description: '',
    price: 0,
    bargain: false,
    progressPayment: false,
    prepayment: false,
    municipalServices: false,
    photos: [],
    userName: '',
    contact: ''
  },
  formSteps: { currentStep: 0, totalSteps: 7 },
  validationErrors: {},
  newPostCreated: false,
  error: {}
}
