// ASYNC
export const ASYNC_ACTION_START = 'ASYNC_ACTION_START'
export const ASYNC_ACTION_FINISH = 'ASYNC_ACTION_FINISH'
export const ASYNC_ACTION_ERROR = 'ASYNC_ACTION_ERROR'
// ALERT
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REMOVE_ALL_ALERTS = 'REMOVE_ALL_ALERTS'
// AUTH
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS'
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGOUT = 'LOGOUT'
// POST
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const UPLOAD_PHOTO = 'UPLOAD_PHOTO'
export const ADD_POST = 'ADD_POST'
export const SET_FILTER = 'SET_FILTER'
export const POST_ERROR = 'POST_ERROR'
