import { Settlement, Post, UserType, EstateType, DealType } from '../types';

export const capitalCity: Settlement = {
  id: '10',
  name: 'Bakı',
  nameRu: 'Баку',
  nameEn: 'Baku',
  routeName: 'baku',
  x: 49.8786270618439,
  y: 40.379108951404,
  children: [
    {
      id: '117',
      name: 'Binəqədi',
      nameRu: 'Бинагади',
      nameEn: 'Binagadi',
      routeName: 'binagadi',
    },
    {
      id: '112',
      name: 'Nərimanov',
      nameRu: 'Нариманов',
      nameEn: 'Narimanov',
      routeName: 'narimanov',
    },
    {
      id: '111',
      name: 'Nəsimi',
      nameRu: 'Насими',
      nameEn: 'Nasimi',
      routeName: 'nasimi',
    },
    {
      id: '113',
      name: 'Nizami',
      nameRu: 'Низами',
      nameEn: 'Nizami',
      routeName: 'nizami',
    },
    {
      id: '122',
      name: 'Pirallahı',
      nameRu: 'Пираллахи',
      nameEn: 'Pirallahi',
      routeName: 'pirallahi',
    },
    {
      id: '121',
      name: 'Qaradağ',
      nameRu: 'Гарадаг',
      nameEn: 'Garadagh',
      routeName: 'garadagh',
    },
    {
      id: '118',
      name: 'Sabunçu',
      nameRu: 'Сабунчи',
      nameEn: 'Sabunchu',
      routeName: 'sabunchu',
    },
    {
      id: '115',
      name: 'Səbail',
      nameRu: 'Сабаил',
      nameEn: 'Sabail',
      routeName: 'sabail',
    },
    {
      id: '119',
      name: 'Suraxanı',
      nameRu: 'Сураханы',
      nameEn: 'Surakhani',
      routeName: 'surakhani',
    },
    {
      id: '114',
      name: 'Xətai',
      nameRu: 'Хатаи',
      nameEn: 'Khatai',
      routeName: 'khatai',
    },
    {
      id: '120',
      name: 'Xəzər',
      nameRu: 'Хазар',
      nameEn: 'Khazar',
      routeName: 'khazar',
    },
    {
      id: '116',
      name: 'Yasamal',
      nameRu: 'Ясамал',
      nameEn: 'Yasamal',
      routeName: 'yasamal',
    },
  ],
};

export const defaultPost: Post = {
  _id: 0,
  active: false,
  userType: UserType.owner,
  estateType: EstateType.house,
  dealType: DealType.sale,
  location: [0, 0],
  city: capitalCity,
  district: capitalCity.children![0],
  address: '',
  rooms: 0,
  lotSqm: 0,
  floor: 0,
  totalFloors: 0,
  sqm: 0,
  description: '',
  images: [],
  price: 0,
  step: 0,
};
