const mongoose = require('mongoose')

const PostSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'user',
      required: true,
    },
    userName: { type: String, required: true },
    userType: { type: String, required: true },
    city: {
      type: {
        name: String,
        id: String,
      },
      required: true,
    },
    district: {
      type: {
        name: String,
        id: String,
        required: true,
      },
      required: true,
    },
    subdistrict: {
      name: String,
      id: String,
    },
    address: { type: String, required: true },
    location: { type: [Number, Number], required: true },
    estateType: { type: String, required: true },
    apartmentType: { type: String, required: true },
    dealType: { type: String, required: true },
    rooms: { type: Number, required: true },
    sqm: { type: Number, required: true },
    livingRoomsSqm: Number,
    kitchenSqm: Number,
    lotSqm: Number,
    floor: Number,
    totalFloors: Number,
    maintenance: String,
    redevelopment: Boolean,
    ceilingHeight: Number,
    yearBuild: Number,
    elevator: Boolean,
    parkingLot: Boolean,
    documented: Boolean,
    mortgage: Boolean,
    kidsAllowed: Boolean,
    petsAllowed: Boolean,
    balcony: Boolean,
    bathroomType: String,
    windows: Number,
    frontWindow: Boolean,
    rearWindow: Boolean,
    furniture: Boolean,
    kitchenFurniture: Boolean,
    cctv: Boolean,
    phone: Boolean,
    internet: Boolean,
    electricity: Boolean,
    gas: Boolean,
    water: Boolean,
    heating: Boolean,
    tv: Boolean,
    conditioner: Boolean,
    washingMachine: Boolean,
    dishwasher: Boolean,
    refrigerator: Boolean,
    garage: Boolean,
    pool: Boolean,
    bathhouse: Boolean,
    description: { type: String, required: true },
    price: { type: Number, required: true },
    bargain: Boolean,
    progressPayment: Boolean,
    prepayment: Boolean,
    municipalServices: Boolean,
    images: { type: Array, required: true },
    contact: { type: String, required: true },
  },
  { timestamps: true }
)

module.exports = Post = mongoose.model('post', PostSchema)
